//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajusxbanc
    {
        public int id_ajxba { get; set; }
        public System.DateTime fecha_ajxba { get; set; }
        public decimal monto_ajxba { get; set; }
        public string no_ajxba { get; set; }
        public string descripcion_ajxba { get; set; }
        public Nullable<System.DateTime> fechae_ajxba { get; set; }
        public Nullable<decimal> tcambio_ajxba { get; set; }
        public bool estado_ajxba { get; set; }
        public Nullable<int> id_ban { get; set; }
    
        public virtual banco banco { get; set; }
    }
}
