//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banco()
        {
            this.ajusxbanc = new HashSet<ajusxbanc>();
            this.histxbanc = new HashSet<histxbanc>();
            this.lotexbanc = new HashSet<lotexbanc>();
            this.pagoxprov = new HashSet<pagoxprov>();
        }
    
        public int id_ban { get; set; }
        public string nombre_ban { get; set; }
        public string cuenta_ban { get; set; }
        public string banco_ban { get; set; }
        public decimal monto_ban { get; set; }
        public Nullable<bool> fi_nf_ban { get; set; }
        public string tipo_ban { get; set; }
        public Nullable<System.DateTime> fechxelim_ban { get; set; }
        public Nullable<bool> estado_ban { get; set; }
        public Nullable<int> id_mon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajusxbanc> ajusxbanc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histxbanc> histxbanc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lotexbanc> lotexbanc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoxprov> pagoxprov { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
