//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public long id_bit { get; set; }
        public Nullable<int> idx_bit { get; set; }
        public string tabla_bit { get; set; }
        public string modulo_bit { get; set; }
        public string area_bit { get; set; }
        public string accion_bit { get; set; }
        public string detalle_bit { get; set; }
        public Nullable<System.DateTime> fecha_bit { get; set; }
        public Nullable<int> idx_emp { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
