//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cambio
    {
        public int id_cam { get; set; }
        public Nullable<bool> estado_cam { get; set; }
        public Nullable<int> id_de_mon { get; set; }
        public Nullable<int> id_a_mon { get; set; }
    
        public virtual moneda moneda { get; set; }
        public virtual moneda moneda1 { get; set; }
    }
}
