//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cheque()
        {
            this.descxcheq = new HashSet<descxcheq>();
        }
    
        public int id_che { get; set; }
        public Nullable<int> correlativo_che { get; set; }
        public Nullable<System.DateTime> fecha_che { get; set; }
        public string no_che { get; set; }
        public string nombre_che { get; set; }
        public Nullable<decimal> monto_che { get; set; }
        public Nullable<decimal> tcambio_che { get; set; }
        public Nullable<bool> rec_ent_che { get; set; }
        public Nullable<short> estado_che { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descxcheq> descxcheq { get; set; }
    }
}
