//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.pagoxclie = new HashSet<pagoxclie>();
            this.venta = new HashSet<venta>();
        }
    
        public int id_cli { get; set; }
        public string nit_cli { get; set; }
        public string nombre_cli { get; set; }
        public string apellido_cli { get; set; }
        public string telefono1_cli { get; set; }
        public string telefono2_cli { get; set; }
        public string correo_cli { get; set; }
        public Nullable<decimal> saldoq_cli { get; set; }
        public Nullable<decimal> saldoc_cli { get; set; }
        public Nullable<decimal> saldod_cli { get; set; }
        public Nullable<bool> credito_cli { get; set; }
        public bool estado_cli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoxclie> pagoxclie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
