//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public int id_con { get; set; }
        public string nombre_con { get; set; }
        public string destino_con { get; set; }
        public byte[] logo_con { get; set; }
        public byte[] banner_con { get; set; }
        public Nullable<bool> bannerbit_con { get; set; }
        public string direccion_con { get; set; }
        public string telefono1_con { get; set; }
        public string telefono2_con { get; set; }
        public string correo_con { get; set; }
        public string web_con { get; set; }
    }
}
