//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenxpaga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuenxpaga()
        {
            this.detaxpago = new HashSet<detaxpago>();
        }
    
        public int id_cuxpa { get; set; }
        public string factura_cuxpa { get; set; }
        public string descripcion_cuxpa { get; set; }
        public decimal monto_cuxpa { get; set; }
        public Nullable<decimal> saldo_cuxpa { get; set; }
        public Nullable<decimal> abonado_cuxpa { get; set; }
        public Nullable<System.DateTime> fecha_cuxpa { get; set; }
        public Nullable<System.DateTime> fechxvenc_cuxpa { get; set; }
        public Nullable<bool> fiscal_cuxpa { get; set; }
        public Nullable<bool> pagado_cuxpa { get; set; }
        public Nullable<bool> estado_cuxpa { get; set; }
        public Nullable<int> id_via { get; set; }
        public Nullable<int> id_mon { get; set; }
        public Nullable<int> id_pro { get; set; }
        public Nullable<int> id_caxcxp { get; set; }
    
        public virtual catexcxp catexcxp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxpago> detaxpago { get; set; }
        public virtual moneda moneda { get; set; }
        public virtual proveedor proveedor { get; set; }
        public virtual viaje viaje { get; set; }
    }
}
