//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class descxcheq
    {
        public long id_dexch { get; set; }
        public Nullable<decimal> monto_dexch { get; set; }
        public Nullable<int> id_che { get; set; }
        public Nullable<int> id_caxch { get; set; }
    
        public virtual catexcheq catexcheq { get; set; }
        public virtual cheque cheque { get; set; }
    }
}
