//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detaxpart
    {
        public long id_dexpa { get; set; }
        public Nullable<decimal> monto_de_dexpa { get; set; }
        public Nullable<decimal> monto_ha_dexpa { get; set; }
        public Nullable<bool> debe_haber_dexpa { get; set; }
        public Nullable<bool> estado_dexpa { get; set; }
        public Nullable<int> id_par { get; set; }
        public Nullable<int> id_nom { get; set; }
    
        public virtual nomenclatura nomenclatura { get; set; }
        public virtual partida partida { get; set; }
    }
}
