//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detaxpaxpr
    {
        public decimal monto_dexpxp { get; set; }
        public Nullable<int> id_cuxpa { get; set; }
        public Nullable<int> id_paxpr { get; set; }
    }
}
