//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detaxpago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detaxpago()
        {
            this.dexpaxlo = new HashSet<dexpaxlo>();
        }
    
        public int id_dexpa { get; set; }
        public Nullable<decimal> monto_dexpa { get; set; }
        public Nullable<decimal> tcambio_dexpa { get; set; }
        public Nullable<decimal> montot_dexpa { get; set; }
        public string descripcion_dexpa { get; set; }
        public Nullable<decimal> saldo_dexpa { get; set; }
        public Nullable<bool> estado_dexpa { get; set; }
        public Nullable<int> id_paxpr { get; set; }
        public Nullable<int> id_cuxpa { get; set; }
    
        public virtual cuenxpaga cuenxpaga { get; set; }
        public virtual pagoxprov pagoxprov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dexpaxlo> dexpaxlo { get; set; }
    }
}
