//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class dexpaxlo
    {
        public int id_dxpxl { get; set; }
        public Nullable<decimal> monto_dxpxl { get; set; }
        public Nullable<bool> estado_dxpxl { get; set; }
        public Nullable<int> id_dexpa { get; set; }
        public Nullable<int> id_loxba { get; set; }
    
        public virtual detaxpago detaxpago { get; set; }
        public virtual lotexbanc lotexbanc { get; set; }
    }
}
