//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public int id_gas { get; set; }
        public string factura_gas { get; set; }
        public Nullable<System.DateTime> fecha_gas { get; set; }
        public string descripcion_gas { get; set; }
        public Nullable<decimal> monto_gas { get; set; }
        public Nullable<bool> estado_gas { get; set; }
        public Nullable<int> id_baxvi { get; set; }
    
        public virtual bancxviaj bancxviaj { get; set; }
    }
}
