//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class histxcajac
    {
        public long id_hixca { get; set; }
        public Nullable<int> idx_hixca { get; set; }
        public string tabla_hixca { get; set; }
        public string acion_hixca { get; set; }
        public Nullable<decimal> saldoi_hixca { get; set; }
        public Nullable<decimal> monto_hixca { get; set; }
        public Nullable<decimal> saldof_hixca { get; set; }
        public Nullable<System.DateTime> fecha_hixca { get; set; }
        public Nullable<int> id_caj { get; set; }
    
        public virtual caja caja { get; set; }
    }
}
