//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lote()
        {
            this.ajusxlote = new HashSet<ajusxlote>();
            this.detaxvent = new HashSet<detaxvent>();
        }
    
        public long id_lot { get; set; }
        public Nullable<int> cantidad_lot { get; set; }
        public Nullable<int> stock_lot { get; set; }
        public Nullable<decimal> preciou_lot { get; set; }
        public Nullable<decimal> preciot_lot { get; set; }
        public Nullable<bool> estado_lot { get; set; }
        public Nullable<int> id_via { get; set; }
        public Nullable<int> id_pre { get; set; }
        public Nullable<int> id_tam { get; set; }
        public Nullable<int> id_pro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajusxlote> ajusxlote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxvent> detaxvent { get; set; }
        public virtual presentacion presentacion { get; set; }
        public virtual producto producto { get; set; }
        public virtual tamano tamano { get; set; }
        public virtual viaje viaje { get; set; }
    }
}
