//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class lotexbanc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lotexbanc()
        {
            this.dexpaxlo = new HashSet<dexpaxlo>();
        }
    
        public int id_loxba { get; set; }
        public Nullable<System.DateTime> fecha_loxba { get; set; }
        public Nullable<decimal> monto_loxba { get; set; }
        public Nullable<decimal> saldo_loxba { get; set; }
        public Nullable<decimal> tcambio_loxba { get; set; }
        public Nullable<bool> estado_loxba { get; set; }
        public Nullable<int> id_ban { get; set; }
    
        public virtual banco banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dexpaxlo> dexpaxlo { get; set; }
    }
}
