//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class memorando
    {
        public int id_mem { get; set; }
        public Nullable<System.DateTime> fecha_mem { get; set; }
        public string descripcion_mem { get; set; }
        public Nullable<decimal> total_mem { get; set; }
        public Nullable<bool> estado_mem { get; set; }
        public Nullable<int> id_via { get; set; }
    
        public virtual viaje viaje { get; set; }
    }
}
