//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomenclatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nomenclatura()
        {
            this.detaxpart = new HashSet<detaxpart>();
        }
    
        public int id_nom { get; set; }
        public Nullable<decimal> no_nom { get; set; }
        public string nombre_nom { get; set; }
        public string descripcion_nom { get; set; }
        public Nullable<int> tipo_nom { get; set; }
        public Nullable<bool> estado_nom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxpart> detaxpart { get; set; }
    }
}
