//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagoxprov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pagoxprov()
        {
            this.datoxpago = new HashSet<datoxpago>();
            this.detaxpago = new HashSet<detaxpago>();
        }
    
        public int id_paxpr { get; set; }
        public System.DateTime fechar_paxpr { get; set; }
        public decimal monto_paxpr { get; set; }
        public Nullable<decimal> tcambio_paxpr { get; set; }
        public Nullable<decimal> montoq_paxpr { get; set; }
        public bool estado_paxpr { get; set; }
        public Nullable<int> id_for { get; set; }
        public Nullable<int> id_ban { get; set; }
        public Nullable<int> id_par { get; set; }
        public string cheque_paxpr { get; set; }
        public string fechac_paxpr { get; set; }
        public string proveedorc_paxpr { get; set; }
        public string sumac_paxpr { get; set; }
        public Nullable<System.DateTime> fechat_paxpr { get; set; }
        public string codigot_paxpr { get; set; }
        public string boletat_paxpr { get; set; }
        public string clientet_paxpr { get; set; }
        public string agenciat_paxpr { get; set; }
        public string numerocht_paxpr { get; set; }
    
        public virtual banco banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datoxpago> datoxpago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxpago> detaxpago { get; set; }
        public virtual formapago formapago { get; set; }
        public virtual partida partida { get; set; }
    }
}
