//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagoxclie
    {
        public int id_paxcl { get; set; }
        public Nullable<decimal> monto_paxcl { get; set; }
        public Nullable<System.DateTime> fecha_paxcl { get; set; }
        public string no1_paxcl { get; set; }
        public string no2_paxcl { get; set; }
        public byte[] imagen_paxcl { get; set; }
        public string descripcion_paxcl { get; set; }
        public Nullable<bool> bit_ba_ca { get; set; }
        public Nullable<int> id_ba_ca { get; set; }
        public Nullable<decimal> tcambio_paxcl { get; set; }
        public Nullable<bool> estado_paxcl { get; set; }
        public Nullable<int> id_for { get; set; }
        public Nullable<int> id_cli { get; set; }
        public Nullable<int> id_mon { get; set; }
        public Nullable<int> id_cuxco { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual cuenxcobr cuenxcobr { get; set; }
        public virtual formapago formapago { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
