//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class partida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partida()
        {
            this.detaxpart = new HashSet<detaxpart>();
            this.pagoxprov = new HashSet<pagoxprov>();
        }
    
        public int id_par { get; set; }
        public Nullable<short> folio_par { get; set; }
        public Nullable<int> no_par { get; set; }
        public Nullable<System.DateTime> fecha_par { get; set; }
        public string descripcion_par { get; set; }
        public Nullable<decimal> totaldebe_par { get; set; }
        public Nullable<decimal> totalhaber_par { get; set; }
        public Nullable<bool> estado_par { get; set; }
        public Nullable<int> id_emp_apr_par { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxpart> detaxpart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagoxprov> pagoxprov { get; set; }
    }
}
