//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.cuenxcobr = new HashSet<cuenxcobr>();
            this.detaxvent = new HashSet<detaxvent>();
        }
    
        public int id_ven { get; set; }
        public string facura_ven { get; set; }
        public System.DateTime fecha_ven { get; set; }
        public decimal total_ven { get; set; }
        public Nullable<bool> credito_ven { get; set; }
        public Nullable<bool> pagado_ven { get; set; }
        public bool estado_ven { get; set; }
        public Nullable<int> id_cli { get; set; }
        public Nullable<int> id_emp { get; set; }
        public Nullable<int> id_mon { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuenxcobr> cuenxcobr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detaxvent> detaxvent { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
